#!/usr/bin/env python

import sys
from pomegranate.server import main

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print "Usage: %s <config-file>" % (sys.argv[0])
        sys.exit(-1)

    main(sys.argv[1])
